
package ca.bcit.a00057006ws.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeServicesService", targetNamespace = "http://services.a00057006ws.bcit.ca/", wsdlLocation = "http://localhost:8080/A00057006ws/EmployeeServices?wsdl")
public class EmployeeServicesService
    extends Service
{

    private final static URL EMPLOYEESERVICESSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEESERVICESSERVICE_EXCEPTION;
    private final static QName EMPLOYEESERVICESSERVICE_QNAME = new QName("http://services.a00057006ws.bcit.ca/", "EmployeeServicesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/A00057006ws/EmployeeServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEESERVICESSERVICE_WSDL_LOCATION = url;
        EMPLOYEESERVICESSERVICE_EXCEPTION = e;
    }

    public EmployeeServicesService() {
        super(__getWsdlLocation(), EMPLOYEESERVICESSERVICE_QNAME);
    }

    public EmployeeServicesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEESERVICESSERVICE_QNAME, features);
    }

    public EmployeeServicesService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEESERVICESSERVICE_QNAME);
    }

    public EmployeeServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEESERVICESSERVICE_QNAME, features);
    }

    public EmployeeServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeServicePort
     */
    @WebEndpoint(name = "EmployeeServicesPort")
    public EmployeeServicePort getEmployeeServicesPort() {
        return super.getPort(new QName("http://services.a00057006ws.bcit.ca/", "EmployeeServicesPort"), EmployeeServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeServicePort
     */
    @WebEndpoint(name = "EmployeeServicesPort")
    public EmployeeServicePort getEmployeeServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.a00057006ws.bcit.ca/", "EmployeeServicesPort"), EmployeeServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEESERVICESSERVICE_EXCEPTION!= null) {
            throw EMPLOYEESERVICESSERVICE_EXCEPTION;
        }
        return EMPLOYEESERVICESSERVICE_WSDL_LOCATION;
    }

}
